
services:
  # PostgreSQL Database
  postgres:
    image: postgres
    container_name: lightforlife_postgres
    environment:
     - POSTGRES_DB=LL_TI
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password_123
    ports:
      - "5440:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis
    container_name: lightforlife_redis
    ports:
      - "6379:6379"
